# Generated by Django 3.1.5 on 2021-01-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210109_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='search',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
