# Generated by Django 3.1.5 on 2021-01-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_order_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='search',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
